### ISSUE TITLE
Add   {bool notify = true}  to `removeElement`

### ISSUE THREAD

**Issue by guchengxi1994** [alnitak/flutter_flow_chart#12]
![image](https://github.com/alnitak/flutter_flow_chart/assets/33513462/424fe721-0020-42eb-a92d-1b31753ec6d2)
I was using this package to build a chart which `addNextById` automatically when adding or remove elements, it is better to add  {bool notify = true} to `removeElement` fuction. Just an advice.

**Comment by alnitak** [comment]
Good point.
I added the same behavior also to `removeAllElements`, `removeElementConnection`, `removeAllElements`, and some other methods.
Thanks for *notifying* me :)
