### ISSUE TITLE
[suggestion] add a `custom` parameter to `FlowElement`

### ISSUE THREAD

**Issue by guchengxi1994** [alnitak/flutter_flow_chart#13]
![image](https://github.com/alnitak/flutter_flow_chart/assets/33513462/4c0ac04f-6d43-4746-abba-ffcb7dd6447c)

Still me. When I use `FlowElement` and save to json, I want to save some custom data with the element but I dont want to display on the flow chart. I think add a `custom` parameter should be helpful.

**Comment by SL-Pirate** [comment]
@guchengxi1994 Your suggestion is indeed thoughtful, and I appreciate your consideration for enhancing the functionality of FlowElement. While I understand the desire for a direct mechanism to store custom data within the FlowElement itself, it's important to maintain the clarity and simplicity of the plugin's core purpose, which is to facilitate the creation of Flow Charts.

Considering the specific context of the plugin, handling custom data may introduce unnecessary complexity and potentially compromise the user experience. However, I do acknowledge the need for such functionality, and I appreciate your workaround using a `Map` to associate custom data with the FlowElement's UUID. This approach effectively separates the plugin-specific data from custom data, providing a practical solution.

Here's a more detailed explanation of the workaround using a `Map`:

```dart
// Define the master data structure
Map<String, dynamic> master = {
  "elements": [
    {
      "id": "element1",
      // plugin specific data
    },
    // other elements
  ],
  "data": {
    "element1": {
      // your custom data associated with the FlowElement's UUID
    },
    // other custom data mappings
  }
};
```

By adopting this approach, you can maintain the integrity of the FlowElement's purpose while offering users the flexibility to include additional information as needed. If you have any further questions or suggestions, feel free to discuss them. Your feedback is valuable in refining the plugin and its features.

**Comment by guchengxi1994** [comment]
@SL-Pirate I think I will use extension on `FlowElement` to storage custom data. Thanks for the answer.

**Comment by SL-Pirate** [comment]
> @SL-Pirate I think I will use extension on `FlowElement` to storage custom data. Thanks for the answer.

That approach sounds quite clever and should serve your needs well. Best of luck with your project, and I appreciate your valuable input on the plugin. If you have any more questions or updates, feel free to share them. Happy coding!

**Comment by hansbak** [comment]
After a bit more study i see that the menus are external and  a custom menu can be added using the  flowElementId in a separate data structure and handled separately....: 

no need for the #15 request of me, i will close it.
