### ISSUE TITLE
add custom data to an element

### ISSUE THREAD

**Issue by hansbak** [alnitak/flutter_flow_chart#15]
Hi, pretty package you have here!
I am looking to use this flowchart editor as a 'workflow' editor for BPMN type of workflow for just the basics.

Therefore it would be nice to be able to add custom data to connections and elements,

When the generated flowchart could be loaded into the flutter [flowbuilder](https://pub.dev/packages/flow_builder) dart package, we could use this flowchart package as a business process modelling tool.

any thoughts about this?
Regards,
Hans

**Comment by alnitak** [comment]
Hi @hansbak,

I think this is feasible. I think we discussed a similar question in the #13 issue. But I don't know if I could do this shortly.

Thanks for your feedback! We could leave this issue open to remember later.

**Comment by hansbak** [comment]
no need can add a selection in the external menus.
