### ISSUE TITLE
reopening issue as I see the same behavior - keyboard window closes before I can type anything

### ISSUE THREAD

**Issue by ndubbaka** [alnitak/flutter_flow_chart#19]
Hello @alnitak ,

Apologies for not responding sooner.

I believe you are correct, StarMenu is still leading to problems.

I just updated all my Flutter packages (picked up the new update), and though I don't see the same exception, I still see the same behavior (i.e., the keyboard window closes before I can type anything).

For now, the current exception is the following:

======== Exception caught by scheduler library =====================================================
E/flutter (31108): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 161 pos 12: '_overlay != null': is not true.
E/flutter (31108): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (31108): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
The following assertion was thrown during a scheduler callback:
Cannot get renderObject of inactive element.
E/flutter (31108): #2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:161:12)

Thank you for all your help.

_Originally posted by @bl12345 in https://github.com/alnitak/flutter_flow_chart/issues/2#issuecomment-1373096417_

**Comment by ndubbaka** [comment]
@alnitak even with the latest code - in Android app, keyboard window closes before I can type anything.

**Comment by alnitak** [comment]
As stated in issue #2 you referenced, this is a `pkg:StarMenu` problem, not related to `flutter_flow_chart`.
I suggest you  to use some alternative methods to ask for text.
