### ISSUE TITLE
Canvas Zoom 

### ISSUE THREAD

**Issue by matteoberla** [alnitak/flutter_flow_chart#20]
I've seen that on issue #5 was asked to add zoom feature of the canvas.
Was it added? I can't find references to it.

**Comment by SL-Pirate** [comment]
No the zoom feature is not added to the package (yet).

**Comment by matteoberla** [comment]
I've seen that the issue was opened over an year ago. will it be added soon?

**Comment by SL-Pirate** [comment]
I hope you are happy :P

**Comment by matteoberla** [comment]
Thank you very much, you are amazing

**Comment by matteoberla** [comment]
I've seen that arrow black dots are not resized as expected

**Comment by matteoberla** [comment]
Also, a callback for `onScaleUpdate` would be useful to manage zoom gesture

**Comment by SL-Pirate** [comment]
> Thank you very much, you are amazing

You are welcome :)
