### ISSUE TITLE
Zoom issues/new features

### ISSUE THREAD

**Issue by matteoberla** [alnitak/flutter_flow_chart#23]
About zoom feature:
-I've seen that arrow black dots are not resized as expected
-callback for `onScaleUpdate` would be useful to manage zoom gesture (on web i can't zoom with the mouse neither with the keyboard)
-if dashboard has a fixed size when zooming in and out the sizes of the dashboard are not updated so i see the element inside the dashboard resized correcly but the dashboard keeps same size

**Comment by SL-Pirate** [comment]
First of all, Thank you for your feedback

> I've seen that arrow black dots are not resized as expected

Good catch. I'll see if I can do something about this

> callback for onScaleUpdate would be useful to manage zoom gesture

Sounds good. Will add in a future update

> on web i can't zoom with the mouse neither with the keyboard

Apparently this is a limitation on the flutter web platform itself where it ignores the scaling gestures. As a workaround, you can use the setZoomFactor method of the Dashboard to update the scale using user input from buttons.

> if dashboard has a fixed size when zooming in and out the sizes of the dashboard are not updated so i see the element inside the dashboard resized correcly but the dashboard keeps same size

This part is a bit unclear, Please elaborate

**Comment by matteoberla** [comment]
> This part is a bit unclear, Please elaborate

I've set the dashboard size (to be similar to an A4 sheet): 
`dashboard.setDashboardSize(const Size(38 * 21, 38 * 29));`

When opening the page i see:
![standardzoom](https://github.com/alnitak/flutter_flow_chart/assets/69200334/8dda1aec-3f08-4292-9b55-aede5009207d)

zoom in:
![zoomed](https://github.com/alnitak/flutter_flow_chart/assets/69200334/3d052b6d-c430-44b6-93be-b187e27fe6fc)

If i zoom in the dashboard keeps its sizes, but i expect it to act as a sheet, so when i zoom in the entire dashboard is zoomed, not only its content.

**Comment by SL-Pirate** [comment]
> If i zoom in the dashboard keeps its sizes, but i expect it to act as a sheet, so when I zoom in the entire dashboard is zoomed, not only its content.

So you want the entire dashboard to get zoomed similar to how an actual paper would look bigger when you look closer?
Okay that's not how it is intended to be here. So if you want that feature what I could do is, as you requested I will implement the onScaleUpdate method so you can update the actual dimensions of the dashboard. 

PS: Sorry for the late reply. It has been a very busy week.

**Comment by matteoberla** [comment]
Yes I think it’s a good solution

Il giorno sab 20 apr 2024 alle 08:01 Isira Herath ***@***.***>
ha scritto:

**Comment by SL-Pirate** [comment]
I pushed the commits. You can start working on your solution as soon as it is merged and published by @alnitak 
Good luck with your project :)

**Comment by matteoberla** [comment]
hi, can i test your changes even if the package is not published yet?

**Comment by alnitak** [comment]
@matteoberla I have published v2.2.1 right now!

**Comment by matteoberla** [comment]
I'm not getting how should i use `onScaleUpdate` as i need to specify it when creating the `Dashboard `object but if i want to set size of dashboard i need a way to reference to the dashboard itself.

when i asked for the implementation of the method i meant inside the FlowChart widget, where all the callbacks are declared.

**Comment by SL-Pirate** [comment]
Yes you are in fact right
It's a short fix and I will push the commits right away.
Thank you for your patience :)

**Comment by matteoberla** [comment]
is there a way to highlight the dashboard boundaries based on the size given?
I'm changing the sizes of the dashboard manually but i'm not getting what is changing

**Comment by matteoberla** [comment]
When zooming in/out and add a new component to the flow chart the sizes don't reflect the zoomfactor so every component has its dimension based on the current zoom factor

**Comment by SL-Pirate** [comment]
> When zooming in/out and add a new component to the flow chart the sizes don't reflect the zoomfactor so every component has its dimension based on the current zoom factor

Yes that is right
Each individual element does not has its own scale/zoom factor. In fact the size of the element itself is updated.

**Comment by matteoberla** [comment]
shouldn't it be better to add the components with the sizes scaled based on the current zoom factor?

**Comment by SL-Pirate** [comment]
It will be difficult due to the current implementation. I'm not telling it's impossible. But it requires a lot of work. 

but you could use the current scale from the dashboard and calculate the relative size of the element
```dart
final actualSize = element.size * dashboard.zoomFactor;
```
