### ISSUE TITLE
fix: 3.2.0 breaks backward compatibility of the JSON format

### ISSUE THREAD

**Issue by ocinon** [alnitak/flutter_flow_chart#36]
When loading a JSON made with the previous version (3.1.1) into 3.2.0, errors occur, as the import in the FlowElement does not contain null checks for newly added data fields.

It would be great if default values were added in the "factory FlowElement.fromMap(Map<String, dynamic> map)" method and everywhere that serialized data gets loaded.

**Comment by alnitak** [comment]
Thank you @ocinon,

an update is coming.
